```{r corpora, echo=F, eval=T, message=F, warning=F, cache=F, results='hide'}  
raw <- corpora$raw
reshaped <- corpora$reshaped
clean <-corpora$clean
pilot <- corpora$pilot
training <- corpora$train
validation <- corpora$validation
test <- corpora$test
```


```{r getData, echo=F, eval=T, message=F, warning=F, cache=T, results='hide'}
getData(raw, referenceFiles, directories, local=TRUE) 
```

```{r reshapeData, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}
parallelizeTask(reshapeData, raw, reshaped, registers)
```

```{r analyzeRawData, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}  
rawDataAnalysis <- parallelizeTask(analyzeData, 'full', reshaped, registers, referenceFiles, directories, regexPatterns)
```

```{r cleanData, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-2), results='hide'}  
parallelizeTask(cleanData, reshaped, clean, registers, referenceFiles, regexPatterns)
```

```{r analyzeCleanData, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}  
cleanDataAnalysis <- parallelizeTask(analyzeData, 'fast', clean, registers, referenceFiles, directories, regexPatterns)  
```
