
```{r pilotDataAnalysis, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-7), results='hide'}  
pilotDataAnalysis <- parallelizeTask(analyzeData, 'fast', pilot, referenceFiles, directories, regexPatterns)
```

```{r diversityAnalysis, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}
diversityAnalysis <- parallelizeTask(analyzeDiversity, pilot, pilotDataAnalysis, directories, regexPatterns)   
```

```{r densityAnalysis, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}
densityAnalysis <- parallelizeTask(analyzeDensity, pilot$pos, posTags, directories)  
```

```{r nGramFrequencies, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
nGramFreqAnalysis <- parallelizeTask(analyzeNGramFrequencies, pilot$nGrams, directories)
```

```{r nGramCoverage, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
nGramCoverage <- parallelizeTask(analyzeNGramCoverage, pilot$nGrams, directories)
```

```{r coverageTrainingAlpha, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-7), results='hide'}     
coverageTrainingAlpha <- parallelizeTask(analyzeNGramCoverageTraining, training$alpha, validation, test, directories)   
```

```{r coverageTrainingBeta, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
coverageTrainingBeta <- parallelizeTask(analyzeNGramCoverageTraining, training$beta, validation, test, directories)   
```

```{r coverageTrainingGamma, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
coverageTrainingGamma <- parallelizeTask(analyzeNGramCoverageTraining, training$gamma, validation, test, directories)   
```

```{r coverageTrainingDelta, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
coverageTrainingDelta <- parallelizeTask(analyzeNGramCoverageTraining, training$delta, validation, test, directories)   
```

```{r coverageSummary, echo=F, eval=T, message=F, warning=F, cache=F, results='hide'}     
coverageSummary <- list(
  alpha = coverageTrainingAlpha,
  beta = coverageTrainingBeta,
  gamma = coverageTrainingGamma,
  delta = coverageTrainingDelta
)
```
