```{r preprocessCorpora, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-12), results='hide'}     
oov <- parallelizeTask(preprocessCorpora, training, validation, test, directories)  
```

```{r processCorpora, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
parallelizeTask(processCorpora, training, validation, test)
```

```{r createNGrams, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
parallelizeTask(createNGrams, training, directories)
```


```{r alphaMkn, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
alphaMkn <- mknPipeline(training$alpha, validation$alpha, lm$mkn,  regexPatterns, directories)
```

```{r betaMkn, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
betaMkn <- mknPipeline(training$beta, validation$beta, lm$mkn, regexPatterns, directories)  
```

```{r gammaMkn, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
gammaMkn <- mknPipeline(training$gamma, validation$gamma, lm$mkn, regexPatterns, directories)
```

```{r deltaMkn, echo=F, eval=T, message=F, warning=F, cache=T, dependson=c(-1), results='hide'}     
deltaMkn <- mknPipeline(training$delta, validation$delta, lm$mkn, regexPatterns, directories)
```
